# -*- coding: utf-8 -*-
"""instagram_experimental.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ad1oHj7QXh86YEpDrX6bAgYIyumD8x7L
"""

!pip install requests_toolbelt

!git clone https://github.com/ricardojoserf/instagram-followers-bot.git

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd instagram-followers-bot

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/instagram_experimental

!git clone https://github.com/realsirjoe/instagram-scraper.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/instagram_experimental/instagram-scraper/examples

# from igramscraper.instagram import Instagram

# instagram = Instagram()

# # authentication supported
# instagram.with_credentials('iluvmahheart1', 'HgLn0@i2x6Zp8Gg')
# instagram.login()

# #Getting an account by id
# account = instagram.get_account_by_id(3)

# # Available fields
# print('Account info:')
# print('Id: ', account.identifier)
# print('Username: ', account.username)
# print('Full name: ', account.full_name)
# print('Biography: ', account.biography)
# print('Profile pic url: ', account.get_profile_picture_url())
# print('External Url: ', account.external_url)
# print('Number of published posts: ', account.media_count)
# print('Number of followers: ', account.followed_by_count)
# print('Number of follows: ', account.follows_count)
# print('Is private: ', account.is_private)
# print('Is verified: ', account.is_verified)

# # or simply for printing use 
# print(account)

from context import Instagram # pylint: disable=no-name-in-module
from time import sleep

instagram = Instagram()
instagram.with_credentials('username', 'password', '/cachepath')
instagram.login(force=False,two_step_verificator=True)

sleep(2) # Delay to mimic user

# username = 'target_user'
# followers = []
# account = instagram.get_account(username)
# sleep(1)
# followers = instagram.get_followers(account.identifier, 150, 100, delayed=True) # Get 150 followers of 'kevin', 100 a time with random delay between requests

# for follower in followers['accounts']:
#     print(follower)





medias = instagram.get_medias("target_username", 25)
media = medias[6]

print(media)



https://www.instagram.com/p/CGxmIHLge2w/

# media_links = []
# like_counter = 0 

i = "https://www.instagram.com/p/CHQ5ovQHXS7/"


for i in media_links:
  
  media = instagram.get_media_by_url(i)

  like_counter = media.likes_count + like_counter









